name: test_scraper

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '38 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        env:
          TODOIST_APIKEY: ${{ secrets.TODOIST_APIKEY }}
        run: |
          python3 test2.py
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "jinwujour@gmail.com"
          git config --global user.name "jinnwuu"
          git diff --quiet || (git add test.json && git commit -m "Updated with latest IPOs")
          git push origin HEAD:main
